apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdocument-all-deployment
spec:
  selector:
    matchLabels:
      app: bigdocument
  replicas: 4
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: bigdocument
    spec:
      containers:
      - name: bigdocument
        image: bigdocument:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bigdocument-all-service
spec:
  type: NodePort
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 80
  selector:
    app: bigdocument
